### ISSUE TITLE
Switch to using aws-sdk-v1 gem

### ISSUE THREAD

**Issue by seeder** [winebarrel/kumogata#41]
aws-sdk is now by default using v2 which is incompatible with kumogata ( AWS vs Aws for example )

**Comment by winebarrel** [comment]
Thank you for your feedback :smiley: 
Please wait.

**Comment by muramasa64** [comment]
:+1:

**Comment by winebarrel** [comment]
Fixed.
v0.5.6 has been released.
Please try it out :smiley:

**Comment by muramasa64** [comment]
My problem is resolved. Thanks!

**Comment by seeder** [comment]
Thank you!
