### ISSUE TITLE
aws-sdk-v2?

### ISSUE THREAD

**Issue by digitaljedi2** [winebarrel/kumogata#45]
Any plans on migrating to the new sdk?  Would you accept PR's if so?

**Comment by winebarrel** [comment]
I will migrate sdk if you have a request.

Of course, I will accept PR. :smiley:

**Comment by digitaljedi2** [comment]
Finished in 0.07057 seconds (files took 0.26413 seconds to load)
72 examples, 64 failures

Looks like I got some work to do ;)

**Comment by n0ts** [comment]
@digitaljedi2 We recommended use https://github.com/winebarrel/kumogata2
